---
strategy: polling
no_screen_padding: 'yes'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: 3.1.8
serverless_language: node
polling_url: https://wasssu.github.io/tv-wall/data/tmdb.json
polling_headers: "."
polling_body: ''
id: 397259
oauth_enabled: 'false'
oauth_pkce_enabled: 'no'
oauth_authorize_url: ''
oauth_token_url: ''
oauth_scopes: ''
oauth_scope_separator: ''
oauth_refresh_url: ''
oauth_auth_params: ''
oauth_token_headers: ''
oauth_token_site: ''
oauth_token_params: ''
oauth_token_request_auth_method: ''
oauth_body_format: ''
oauth_token_response_metadata: ''
oauth_authorization_method: ''
oauth_refresh_params: ''
oauth_token_field_name: ''
oauth_expiry_field_name: ''
oauth_expiry_strategy: ''
oauth_fixed_expiry_ms: ''
custom_fields:
- keyname: about
  field_type: author_bio
  name: About This Plugin
  description: Trending TV Shows (TMDB)
  category: entertainment
  email_address: xtrmnlx@gmail.com
name: TV Wall
refresh_interval: 60
